{
 "title": "CPU Consumption",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage over 10s - Kafka Streams",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"streams-1|streams-2|streams-3\"}[10s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage over 10s - Streamiz",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"streamiz-1|streamiz-2|streamiz-3\"}[10s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage over 10s - Weather Stations",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"weather-station\"}[10s])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}